//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationBlog_DejanSavanovic.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blog()
        {
            this.Komentars = new HashSet<Komentar>();
            this.Slikas = new HashSet<Slika>();
            this.Korisniks = new HashSet<Korisnik>();
        }
    
        public int BlogId { get; set; }
        public int KorisnikId { get; set; }
        public int DrzavaId { get; set; }
        public string Naslov { get; set; }
        public string Sadrzaj { get; set; }
        public Nullable<System.DateTime> DatumPutovanja { get; set; }
        public string NaslovnaSlikaLink { get; set; }
        public System.DateTime DatumKreiranja { get; set; }
        public bool Odobren { get; set; }
    
        public virtual Drzava Drzava { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Komentar> Komentars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Slika> Slikas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Korisnik> Korisniks { get; set; }
    }
}
