//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationBlog_DejanSavanovic.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slika
    {
        public int SlikaId { get; set; }
        public int BlogId { get; set; }
        public string Link { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
